// <auto-generated>
// Generated by figma-flutter-agent. Do not edit by hand.
// </auto-generated>

import 'package:flutter/material.dart';
import 'package:demo_app/theme/app_layout.dart';
import 'package:demo_app/generated/catalog_screen_layout.dart';
import 'package:demo_app/theme/app_spacing.dart';

// <custom-code>
// </custom-code>

/// Responsive shell injected by the generator for web/tablet max width.
class GeneratedScreenShell extends StatelessWidget {
  const GeneratedScreenShell({
    super.key,
    required this.child,
    this.maxWebWidth = 1200,
  });

  final Widget child;
  final double maxWebWidth;

  @override
  Widget build(BuildContext context) {
    final layout = Theme.of(context).extension<AppLayoutExtension>();
    final resolvedMaxWidth = layout?.maxWebWidth ?? maxWebWidth;
    return SafeArea(
      child: LayoutBuilder(
        builder: (context, constraints) {
          final width = constraints.maxWidth;
          final horizontalPadding = AppBreakpoints.horizontalPadding(width);
          final contentMaxWidth = AppBreakpoints.contentMaxWidth(width, resolvedMaxWidth);
          return Align(
            alignment: Alignment.topCenter,
            child: ConstrainedBox(
              constraints: BoxConstraints(maxWidth: contentMaxWidth),
              child: Padding(
                padding: EdgeInsets.symmetric(horizontal: horizontalPadding),
                child: child,
              ),
            ),
          );
        },
      ),
    );
  }
}

class CatalogScreen extends StatelessWidget {
  const CatalogScreen({super.key});

  @override
  Widget build(BuildContext context) {
    final textScaler = MediaQuery.textScalerOf(context);
    return Scaffold(
      appBar: AppBar(title: Text('Catalog Screen', textScaler: textScaler)),
      body: GeneratedScreenShell(child: const CatalogScreenLayout()),
    );
  }
}
