"""Discord bot unit tests."""

from __future__ import annotations

import pytest

from control_panel.bot.access import is_authorized
from control_panel.config.models import (
    AccessMode,
    CustomCodePolicy,
    DiscordAccessConfig,
    DiscordBotYamlConfig,
    DiscordSectionConfig,
)
from control_panel.db import JobStatus, Quality
from control_panel.publish.migrate import default_new_target_path
from control_panel.publish.policy import apply_custom_code_policy
from control_panel.runner.feature_slug import infer_feature_slug
from control_panel.runner.preview import build_preview_session, hash_preview_token
from control_panel.runner.provision import ensure_user_project


@pytest.mark.control_panel
def test_infer_feature_slug_from_feature_first_path() -> None:
    files = ["lib/features/bank_home/screens/bank_home_screen.dart"]
    assert infer_feature_slug(files) == "bank_home"


@pytest.mark.control_panel
@pytest.mark.asyncio
async def test_job_store_create_and_update(job_store, tmp_path) -> None:
    job = await job_store.create_job(
        job_id="abc124",
        figma_url="https://www.figma.com/design/x/y?node-id=1-2",
        discord_user_id=42,
        discord_channel_id=99,
        project_dir=tmp_path / "proj",
    )
    assert job.status == JobStatus.CREATED
    updated = await job_store.update_job("abc124", status=JobStatus.PIPELINE_RUNNING.value)
    assert updated is not None
    assert updated.status == JobStatus.PIPELINE_RUNNING


@pytest.mark.control_panel
def test_preview_session_token_hash() -> None:
    from control_panel.config.models import PreviewConfig

    session = build_preview_session(job_id="job1", config=PreviewConfig())
    assert hash_preview_token(session.token) == session.token_hash
    assert session.fixed_url.startswith("figma-flutter://preview/job1")


@pytest.mark.control_panel
def test_provision_user_project(tmp_path) -> None:
    project_dir = tmp_path / "user_app"
    resolved = ensure_user_project(project_dir)
    assert (resolved / "pubspec.yaml").is_file()


@pytest.mark.control_panel
def test_access_allowlist_denies_unknown_user() -> None:
    yaml_config = DiscordBotYamlConfig(
        discord=DiscordSectionConfig(
            access=DiscordAccessConfig(
                mode=AccessMode.ALLOWLIST,
                allowed_user_ids=[111],
            )
        )
    )

    class _Author:
        id = 222

    class _Inter:
        author = _Author()
        guild = None

    assert is_authorized(_Inter(), yaml_config) is False


@pytest.mark.control_panel
def test_quality_enum_values() -> None:
    assert Quality.GOOD.value == "good"


@pytest.mark.control_panel
def test_default_new_target_path() -> None:
    assert default_new_target_path("bank_home").endswith("bank_home_screen.dart")


@pytest.mark.control_panel
def test_preserve_custom_policy_merges_zones(tmp_path) -> None:
    existing = tmp_path / "screen.dart"
    existing.write_text(
        "// <auto-generated>\nold\n// </auto-generated>\n\n"
        "// <custom-code>\nfinal flag = true;\n// </custom-code>\n",
        encoding="utf-8",
    )
    merged = apply_custom_code_policy(
        policy=CustomCodePolicy.PRESERVE_CUSTOM,
        relative_path="lib/features/a/a_screen.dart",
        generated_content="// <auto-generated>\nnew\n// </auto-generated>\n\n// <custom-code>\n// </custom-code>\n",
        existing_path=existing,
    )
    assert "final flag = true;" in merged
    assert "new" in merged
