// DEBUG BUNDLE — not for compilation.
// Feature: home
// Single-file view of screen + inlined widgets/layout from this generation run.
// Generated by figma-flutter-agent.

import 'package:flutter/material.dart';

// --- begin lib/features/home/home_screen.dart ---
class HomeScreen extends StatelessWidget {
  const HomeScreen({super.key});
  @override
  Widget build(BuildContext context) => const SizedBox.shrink();
}
// --- end lib/features/home/home_screen.dart ---
