"""LLM generation, repair, asset, and font schema models."""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, model_validator

from figma_flutter_agent.schemas.ir import ScreenIr, WidgetIrNode, WidgetIrOverrides


class ExtractedWidget(BaseModel):
    """Reusable widget generated by the LLM."""

    model_config = ConfigDict(populate_by_name=True, extra="forbid")

    widget_name: str = Field(alias="widgetName")
    code: str | None = None
    widget_ir: WidgetIrNode | None = Field(default=None, alias="widgetIr")

    @model_validator(mode="after")
    def _require_widget_payload(self) -> ExtractedWidget:
        has_ir = self.widget_ir is not None
        has_code = bool((self.code or "").strip())
        if not has_ir and not has_code:
            msg = "ExtractedWidget requires widgetIr or code"
            raise ValueError(msg)
        return self

    def resolved_code(self) -> str:
        """Return Dart widget class source when already materialized."""
        return (self.code or "").strip()


class FlutterGenerationResponse(BaseModel):
    """Structured LLM output for Dart generation."""

    model_config = ConfigDict(populate_by_name=True, extra="forbid")

    screen_code: str | None = Field(default=None, alias="screenCode")
    screen_ir: ScreenIr | None = Field(default=None, alias="screenIr")
    extracted_widgets: list[ExtractedWidget] = Field(default_factory=list, alias="extractedWidgets")

    @model_validator(mode="after")
    def _require_screen_payload(self) -> FlutterGenerationResponse:
        has_ir = self.screen_ir is not None
        has_code = bool((self.screen_code or "").strip())
        if not has_ir and not has_code:
            msg = "FlutterGenerationResponse requires screenIr or screenCode"
            raise ValueError(msg)
        return self

    def resolved_screen_code(self) -> str:
        """Return legacy screen Dart when present."""
        return (self.screen_code or "").strip()


class FlutterRepairPatch(BaseModel):
    """One scoped Dart repair patch for analyze failures."""

    model_config = ConfigDict(populate_by_name=True, extra="forbid")

    target: Literal["screenCode", "extractedWidget"]
    widget_name: str | None = Field(default=None, alias="widgetName")
    code: str


class FlutterRepairIrPatch(BaseModel):
    """Structured screen IR patch."""

    model_config = ConfigDict(populate_by_name=True, extra="forbid")

    figma_id: str = Field(alias="figmaId")
    replace_subtree: WidgetIrNode | None = Field(default=None, alias="replaceSubtree")
    overrides: WidgetIrOverrides | None = None
    reorder_children: list[str] | None = Field(default=None, alias="reorderChildren")


class FlutterRepairPatchResponse(BaseModel):
    """Structured LLM output for scoped analyze repair."""

    model_config = ConfigDict(populate_by_name=True, extra="forbid")

    patches: list[FlutterRepairPatch] = Field(default_factory=list)
    ir_patches: list[FlutterRepairIrPatch] = Field(default_factory=list, alias="irPatches")


class RepairCpiSupervisorResponse(BaseModel):
    """Metacognitive interrupt when analyze repair stagnates."""

    model_config = ConfigDict(populate_by_name=True, extra="forbid")

    analysis: str
    pattern_interrupt_directive: str = Field(alias="patternInterruptDirective")


class AssetManifestEntry(BaseModel):
    """Exported asset metadata."""

    model_config = ConfigDict(extra="forbid")

    node_id: str
    asset_path: str
    kind: Literal["icon", "image", "illustration"]
    svg_has_filter: bool = False
    svg_path_count: int | None = None


class AssetManifest(BaseModel):
    """Collection of exported assets."""

    model_config = ConfigDict(extra="forbid")

    entries: list[AssetManifestEntry] = Field(default_factory=list)


class FontFaceRequirement(BaseModel):
    """Unique font face referenced by generated TEXT nodes."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    figma_family: str
    font_weight: str = Field(default="w400", alias="fontWeight")
    font_style: str | None = Field(default=None, alias="fontStyle")


class FontPubspecAsset(BaseModel):
    """Single font asset entry for pubspec.yaml."""

    model_config = ConfigDict(extra="forbid")

    asset: str
    weight: int
    style: str | None = None


class FontPubspecFamily(BaseModel):
    """Font family block for pubspec.yaml."""

    model_config = ConfigDict(extra="forbid")

    family: str
    fonts: list[FontPubspecAsset] = Field(default_factory=list)


class FontManifest(BaseModel):
    """Bundled fonts exported for a generation run."""

    model_config = ConfigDict(extra="forbid")

    families: list[FontPubspecFamily] = Field(default_factory=list)
    bundled_family_names: list[str] = Field(default_factory=list)
    family_aliases: dict[str, str] = Field(default_factory=dict)
    dart_weight_overrides_by_family: dict[str, dict[str, str]] = Field(default_factory=dict)
    warnings: list[str] = Field(default_factory=list)


def merge_asset_manifests(base: AssetManifest, extra: AssetManifest) -> AssetManifest:
    """Merge exported assets without duplicating node ids."""
    seen = {entry.node_id for entry in base.entries}
    for entry in extra.entries:
        if entry.node_id in seen:
            continue
        base.entries.append(entry)
        seen.add(entry.node_id)
    return base
