// <auto-generated>

// Generated by figma-flutter-agent. Do not edit by hand.

// </auto-generated>



import 'package:flutter/material.dart';



import 'app_colors.dart';

import 'app_layout.dart';



// <custom-code>

// </custom-code>



class AppTheme {

  AppTheme._();



  static ThemeData light({double maxWebWidth = 1200}) {

    return ThemeData(

      useMaterial3: true,

      colorScheme: ColorScheme.fromSeed(

        seedColor: AppColors.primary,

        brightness: Brightness.light,

      ),

      extensions: <ThemeExtension<dynamic>>[

        AppLayoutExtension(maxWebWidth: maxWebWidth),

      ],

    );

  }


}
