"""Golden capture planned files and import-order invariants for wizard view."""

from __future__ import annotations

from pathlib import Path

from figma_flutter_agent.config import Settings, load_settings
from figma_flutter_agent.dev.view_render_plan import planned_for_capture
from figma_flutter_agent.generator.writing.core import DartWriter
from figma_flutter_agent.schemas.tree import CleanDesignTreeNode
from figma_flutter_agent.validation.golden_capture.paths import (
    capture_test_relative_path,
    golden_test_relative_path,
)
from figma_flutter_agent.validation.golden_capture.project import (
    _copy_skeleton_project,
    _materialize_capture_workspace,
)


def test_materialize_debug_bundle_screen_keeps_imports_before_class(tmp_path: Path) -> None:
    project = tmp_path / "demo"
    project.mkdir()
    (project / "pubspec.yaml").write_text("name: demo\n", encoding="utf-8")
    feature = "login_version_1"
    bundle = "\n".join(
        [
            "import 'package:flutter/material.dart';",
            f"// --- begin lib/generated/{feature}_layout.dart ---",
            "class LoginVersion1Layout extends StatelessWidget {",
            "  const LoginVersion1Layout({super.key});",
            "  @override",
            "  Widget build(BuildContext context) => const SizedBox();",
            "}",
            f"// --- end lib/generated/{feature}_layout.dart ---",
            f"// --- begin lib/features/{feature}/{feature}_screen.dart ---",
            "class LoginVersion1Screen extends StatelessWidget {",
            "  const LoginVersion1Screen({super.key});",
            "  @override",
            "  Widget build(BuildContext context) => const LoginVersion1Layout();",
            "}",
            f"// --- end lib/features/{feature}/{feature}_screen.dart ---",
        ]
    )
    bundle_path = tmp_path / "screen.dart"
    bundle_path.write_text(bundle, encoding="utf-8")
    settings = load_settings()
    planned = planned_for_capture(
        project,
        feature_name=feature,
        bundle_path=bundle_path,
        settings=settings,
        clean_tree=None,
    )
    capture_dir = tmp_path / "capture"
    _copy_skeleton_project(capture_dir)
    _materialize_capture_workspace(
        capture_dir,
        planned,
        enable_backup=False,
        layout_tree=None,
        project_dir=project,
    )
    screen_path = capture_dir / "lib/features/login_version_1/login_version_1_screen.dart"
    content = screen_path.read_text(encoding="utf-8")
    import_idx = content.index("import 'package:flutter/material.dart';")
    class_idx = content.index("class LoginVersion1Screen")
    assert import_idx < class_idx


def test_dart_writer_finalize_layout_delegate_screen(tmp_path: Path) -> None:
    project = tmp_path / "demo"
    project.mkdir()
    screen_path = "lib/features/login_version_1/login_version_1_screen.dart"
    content = "\n".join(
        [
            "// <auto-generated>",
            "// Do not edit by hand.",
            "",
            "import 'package:flutter/material.dart';",
            "import 'package:demo/generated/login_version_1_layout.dart';",
            "",
            "class LoginVersion1Screen extends StatelessWidget {",
            "  const LoginVersion1Screen({super.key});",
            "  @override",
            "  Widget build(BuildContext context) => const LoginVersion1Layout();",
            "}",
            "",
        ]
    )
    writer = DartWriter(project, enable_backup=False)
    writer.write_files({screen_path: content})
    written = (project / screen_path).read_text(encoding="utf-8")
    import_idx = written.index("import 'package:flutter/material.dart';")
    class_idx = written.index("class LoginVersion1Screen")
    assert import_idx < class_idx


def _minimal_bundle(project_dir: Path, feature: str) -> Path:
    bundle = project_dir / "bundle.dart"
    bundle.write_text(
        "\n".join(
            [
                "import 'package:flutter/material.dart';",
                f"// --- begin lib/generated/{feature}_layout.dart ---",
                "class LoginVersion1Layout extends StatelessWidget {",
                "  const LoginVersion1Layout({super.key});",
                "  @override",
                "  Widget build(BuildContext context) => const SizedBox();",
                "}",
                f"// --- end lib/generated/{feature}_layout.dart ---",
                f"// --- begin lib/features/{feature}/{feature}_screen.dart ---",
                "class LoginVersion1Screen extends StatelessWidget {",
                "  const LoginVersion1Screen({super.key});",
                "  @override",
                "  Widget build(BuildContext context) => const LoginVersion1Layout();",
                "}",
                f"// --- end lib/features/{feature}/{feature}_screen.dart ---",
            ]
        ),
        encoding="utf-8",
    )
    return bundle


def test_planned_for_capture_includes_golden_test_when_configured(tmp_path: Path) -> None:
    project = tmp_path / "demo"
    project.mkdir()
    (project / "pubspec.yaml").write_text("name: demo\n", encoding="utf-8")
    feature = "login_version_1"
    bundle = _minimal_bundle(project, feature)
    base = Settings()
    settings = base.model_copy(
        update={
            "agent": base.agent.model_copy(
                update={
                    "runtime": base.agent.runtime.model_copy(
                        update={"golden_capture": "docker"},
                    ),
                    "validation": base.agent.validation.model_copy(
                        update={"generate_golden_test": True},
                    ),
                },
            ),
        },
    )
    tree = CleanDesignTreeNode(
        id="root",
        name="Root",
        type="CONTAINER",
        sizing={"width": 375, "height": 812},
        children=[],
    )

    planned = planned_for_capture(
        project,
        feature_name=feature,
        bundle_path=bundle,
        settings=settings,
        clean_tree=tree,
    )

    assert capture_test_relative_path(feature) in planned
    assert golden_test_relative_path(feature) in planned
