from pathlib import Path
from unittest.mock import patch

import pytest

from figma_flutter_agent.errors import GenerationError
from figma_flutter_agent.generator.writer import (
    DartWriter,
    _WriteRecord,
    find_orphan_line_numbers,
    format_orphan_edit_message,
    merge_custom_code,
)


def test_find_orphan_line_numbers_ignores_brace_only_lines() -> None:
    content = "\n".join(
        [
            "// <auto-generated>",
            "class Generated {",
            "  void build() {",
            "}",
            "// </auto-generated>",
            "}",
            ")",
        ]
    )

    assert find_orphan_line_numbers(content) == []


def test_find_orphan_line_numbers_outside_zones() -> None:
    content = "\n".join(
        [
            "// <auto-generated>",
            "class Generated {}",
            "// </auto-generated>",
            "void manualEdit() {}",
            "// <custom-code>",
            "void kept() {}",
            "// </custom-code>",
        ]
    )

    assert find_orphan_line_numbers(content) == [4]


def test_write_files_warns_on_orphan_edits(tmp_path: Path) -> None:
    from loguru import logger

    project_dir = tmp_path / "project"
    project_dir.mkdir()
    target = project_dir / "lib" / "theme" / "app_colors.dart"
    target.parent.mkdir(parents=True)
    target.write_text(
        "\n".join(
            [
                "// <auto-generated>",
                "class Generated {}",
                "// </auto-generated>",
                "const manual = 1;",
            ]
        ),
        encoding="utf-8",
    )

    messages: list[str] = []
    handler_id = logger.add(lambda message: messages.append(message.record["message"]))
    try:
        writer = DartWriter(project_dir)
        writer.write_files(
            {"lib/theme/app_colors.dart": "// <auto-generated>\n// </auto-generated>"}
        )
    finally:
        logger.remove(handler_id)

    assert any("preservation zones" in message for message in messages)


def test_format_orphan_edit_message_includes_line_preview() -> None:
    content = "\n".join(
        [
            "// <auto-generated>",
            "class Generated {}",
            "// </auto-generated>",
            "const manual = 1;",
        ]
    )
    message = format_orphan_edit_message("lib/theme/app_colors.dart", content, [4])
    assert "L4:" in message
    assert "const manual = 1" in message


def test_strict_preservation_blocks_orphan_edits(tmp_path: Path) -> None:
    project_dir = tmp_path / "project"
    project_dir.mkdir()
    target = project_dir / "lib" / "theme" / "app_colors.dart"
    target.parent.mkdir(parents=True)
    target.write_text(
        "\n".join(
            [
                "// <auto-generated>",
                "class Generated {}",
                "// </auto-generated>",
                "const manual = 1;",
            ]
        ),
        encoding="utf-8",
    )

    writer = DartWriter(project_dir, strict_preservation=True)
    with pytest.raises(GenerationError, match="L4: const manual"):
        writer.write_files(
            {"lib/theme/app_colors.dart": "// <auto-generated>\n// </auto-generated>"}
        )


def test_write_files_preserves_custom_code_block(tmp_path: Path) -> None:
    project_dir = tmp_path / "project"
    project_dir.mkdir()
    target = project_dir / "lib" / "features" / "onboarding" / "onboarding_screen.dart"
    target.parent.mkdir(parents=True)
    target.write_text(
        "\n".join(
            [
                "// <auto-generated>",
                "// <custom-code>",
                "void _onContinue() {}",
                "// </custom-code>",
                "class OldScreen {}",
            ]
        ),
        encoding="utf-8",
    )

    new_content = "\n".join(
        [
            "// <auto-generated>",
            "// <custom-code>",
            "// </custom-code>",
            "class OnboardingScreen {}",
        ]
    )

    writer = DartWriter(project_dir)
    writer.write_files({"lib/features/onboarding/onboarding_screen.dart": new_content})

    result = target.read_text(encoding="utf-8")
    assert "void _onContinue() {}" in result
    assert "class OnboardingScreen {}" in result
    assert "// <custom-code>" in result
    assert "// </custom-code>" in result


def test_merge_custom_code_returns_new_content_without_markers() -> None:
    existing = "// <custom-code>\nkeep()\n// </custom-code>"
    new_content = "class Generated {}"

    merged = merge_custom_code(new_content, existing)
    assert "keep()" in merged
    assert "class Generated {}" in merged
    assert "class Generated {}" in merged


def test_rollback_deletes_only_newly_created_files(tmp_path: Path) -> None:
    backup_dir = tmp_path / "backup"
    backup_dir.mkdir()
    project_dir = tmp_path / "project"
    project_dir.mkdir()

    existing = project_dir / "lib" / "theme" / "custom.dart"
    existing.parent.mkdir(parents=True)
    existing.write_text("user content", encoding="utf-8")

    created = project_dir / "lib" / "features" / "onboarding" / "onboarding_screen.dart"
    created.parent.mkdir(parents=True)
    created.write_text("generated", encoding="utf-8")

    writer = DartWriter(project_dir)
    writer._restore_backup(
        backup_dir,
        [
            _WriteRecord(target=existing, existed_before=True),
            _WriteRecord(target=created, existed_before=False),
        ],
    )

    assert existing.exists()
    assert not created.exists()


def test_rollback_preserves_preexisting_file_without_backup(tmp_path: Path) -> None:
    backup_dir = tmp_path / "backup"
    backup_dir.mkdir()
    project_dir = tmp_path / "project"
    project_dir.mkdir()

    existing = project_dir / "lib" / "theme" / "app_colors.dart"
    existing.parent.mkdir(parents=True)
    existing.write_text("partial overwrite", encoding="utf-8")

    writer = DartWriter(project_dir, enable_backup=False)
    writer._restore_backup(backup_dir, [_WriteRecord(target=existing, existed_before=True)])

    assert existing.read_text(encoding="utf-8") == "partial overwrite"


def test_write_files_cleans_up_backup_dir_on_success(tmp_path: Path) -> None:
    project_dir = tmp_path / "project"
    project_dir.mkdir()
    target = project_dir / "lib" / "theme" / "app_colors.dart"

    writer = DartWriter(project_dir)
    with patch("figma_flutter_agent.generator.writer.shutil.rmtree") as rmtree_mock:
        batch = writer.write_files({"lib/theme/app_colors.dart": "generated"})
        writer.commit_batch(batch)
        rmtree_mock.assert_called_once()

    assert "generated" in target.read_text(encoding="utf-8")


def test_atomic_write_keeps_original_when_replace_fails(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    project_dir = tmp_path / "project"
    project_dir.mkdir()
    target = project_dir / "lib" / "theme" / "app_colors.dart"
    target.parent.mkdir(parents=True)
    target.write_text("original", encoding="utf-8")

    original_replace = Path.replace

    def fail_replace(self: Path, other: Path) -> Path:
        if self.name.endswith(".tmp"):
            raise OSError("replace failed")
        return original_replace(self, other)

    monkeypatch.setattr(Path, "replace", fail_replace)

    writer = DartWriter(project_dir)
    with pytest.raises(GenerationError, match="replace failed"):
        writer.write_files({"lib/theme/app_colors.dart": "generated"})

    assert target.read_text(encoding="utf-8") == "original"


def test_rollback_fails_fast_when_unlink_fails(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    backup_dir = tmp_path / "backup"
    backup_dir.mkdir()
    project_dir = tmp_path / "project"
    project_dir.mkdir()

    first = project_dir / "lib" / "a.dart"
    second = project_dir / "lib" / "b.dart"
    first.parent.mkdir(parents=True)
    first.write_text("first", encoding="utf-8")
    second.write_text("second", encoding="utf-8")

    original_unlink = Path.unlink

    def patched_unlink(self: Path, missing_ok: bool = False) -> None:
        if self.name == "b.dart":
            raise OSError("locked")
        original_unlink(self, missing_ok=missing_ok)

    monkeypatch.setattr(Path, "unlink", patched_unlink)

    writer = DartWriter(project_dir)
    with pytest.raises(GenerationError, match="Rollback failed after partial restore"):
        writer._restore_backup(
            backup_dir,
            [
                _WriteRecord(target=first, existed_before=False),
                _WriteRecord(target=second, existed_before=False),
            ],
        )

    assert not first.exists()
    assert second.exists()


def test_write_files_rejects_path_traversal(tmp_path: Path) -> None:
    project_dir = tmp_path / "project"
    project_dir.mkdir()
    writer = DartWriter(project_dir)

    with pytest.raises(GenerationError, match="outside project directory"):
        writer.write_files({"../escape.dart": "void main() {}"})
