"""Refresh compiler-owned bootstrap entrypoints in planned Dart."""

from __future__ import annotations

from dataclasses import dataclass

from loguru import logger

from .paths import drop_planned_path_aliases, planned_content_for_path

_COMPILER_BOOTSTRAP_PATH = "lib/main.dart"
_AGENT_BOOTSTRAP_CLASS = "FigmaFlutterApp"
_AGENT_GENERATED_MARKER = "Generated by figma-flutter-agent"


@dataclass(frozen=True)
class PlannedBootstrapContext:
    """Inputs required to re-render ``lib/main.dart`` for a pipeline run."""

    feature_name: str
    screen_class: str
    app_title: str
    routing_type: str
    routing_enabled: bool
    generate_dark_mode: bool
    max_web_width: int
    architecture: str
    package_name: str
    use_package_imports: bool
    state_management_type: str
    theme_variant: str


def is_agent_generated_bootstrap(content: str) -> bool:
    """True when ``content`` is the figma-flutter bootstrap ``main.dart`` template."""
    return (
        _AGENT_GENERATED_MARKER in content
        and f"class {_AGENT_BOOTSTRAP_CLASS}" in content
    )


def bootstrap_main_needs_refresh(content: str) -> bool:
    """True when planned ``lib/main.dart`` should be replaced before emit gates."""
    from figma_flutter_agent.generator.dart.llm_codegen import validate_dart_delimiters

    if not content.strip():
        return True
    if validate_dart_delimiters(content) is not None:
        return True
    return not is_agent_generated_bootstrap(content)


def build_planned_bootstrap_context(
    *,
    settings,
    package_name: str,
    feature_name: str,
    screen_class: str | None = None,
    app_title: str | None = None,
    routing_on: bool = False,
) -> PlannedBootstrapContext:
    """Build bootstrap render inputs from pipeline settings."""
    from figma_flutter_agent.parser.navigation import _screen_class_name

    generation_cfg = settings.agent.generation
    return PlannedBootstrapContext(
        feature_name=feature_name,
        screen_class=screen_class or _screen_class_name(feature_name),
        app_title=app_title or feature_name.replace("_", " ").title(),
        routing_type=settings.agent.routing.type,
        routing_enabled=routing_on,
        generate_dark_mode=settings.agent.dark_mode.enabled,
        max_web_width=settings.agent.responsive.max_web_width,
        architecture=settings.agent.flutter.architecture,
        package_name=package_name,
        use_package_imports=generation_cfg.use_package_imports,
        state_management_type=settings.agent.state_management.type,
        theme_variant=settings.agent.theme.variant,
    )


def render_planned_bootstrap_files(context: PlannedBootstrapContext) -> dict[str, str]:
    """Render compiler-owned bootstrap files for ``context``."""
    from figma_flutter_agent.generator.renderer import DartRenderer

    renderer = DartRenderer()
    return renderer.render_app_bootstrap(
        feature_name=context.feature_name,
        screen_class=context.screen_class,
        app_title=context.app_title,
        routing_type=context.routing_type,
        routing_enabled=context.routing_enabled,
        generate_dark_mode=context.generate_dark_mode,
        max_web_width=context.max_web_width,
        architecture=context.architecture,  # type: ignore[arg-type]
        package_name=context.package_name,
        use_package_imports=context.use_package_imports,
        state_management_type=context.state_management_type,
        theme_variant=context.theme_variant,
    )


def _existing_bootstrap_content(planned: dict[str, str]) -> str:
    located = planned_content_for_path(planned, _COMPILER_BOOTSTRAP_PATH)
    return located[1] if located is not None else ""


def ensure_compiler_bootstrap_planned_files(
    planned: dict[str, str],
    *,
    bootstrap_files: dict[str, str],
    merge_custom_code: bool = True,
    force: bool = False,
) -> dict[str, str]:
    """Overwrite stale or foreign ``lib/main.dart`` bodies with compiler bootstrap output.

    Args:
        planned: Planned project-relative Dart sources.
        bootstrap_files: Fresh bootstrap files from :func:`render_planned_bootstrap_files`.
        merge_custom_code: When True, preserve ``<custom-code>`` blocks from the prior
            planned body onto the refreshed bootstrap.
        force: When True, always replace the canonical bootstrap path and drop aliases.

    Returns:
        Updated planned mapping.
    """
    if _COMPILER_BOOTSTRAP_PATH not in bootstrap_files:
        return planned

    updated = dict(planned)
    existing = _existing_bootstrap_content(updated)
    fresh = bootstrap_files[_COMPILER_BOOTSTRAP_PATH]
    if not force and not bootstrap_main_needs_refresh(existing):
        drop_planned_path_aliases(updated, _COMPILER_BOOTSTRAP_PATH)
        if existing:
            updated[_COMPILER_BOOTSTRAP_PATH] = existing
        return updated

    if merge_custom_code and existing.strip():
        from figma_flutter_agent.generator.writing.custom_code import merge_custom_code

        fresh = merge_custom_code(fresh, existing)

    for key in list(updated.keys()):
        if key.replace("\\", "/") == _COMPILER_BOOTSTRAP_PATH:
            updated.pop(key, None)
    updated[_COMPILER_BOOTSTRAP_PATH] = fresh
    logger.info("Refreshed compiler bootstrap entrypoint: {}", _COMPILER_BOOTSTRAP_PATH)
    return updated
