// <auto-generated>
// Generated by figma-flutter-agent. Do not edit by hand.
// </auto-generated>

import 'package:flutter/material.dart';

import 'package:demo_app/theme/app_colors.dart';
import 'package:demo_app/theme/app_spacing.dart';

// <custom-code>
// </custom-code>

class TitleWidget extends StatelessWidget {
  const TitleWidget({super.key});

  @override
  Widget build(BuildContext context) {
    final textScaler = MediaQuery.textScalerOf(context);
    return Semantics(label: 'Title', child: Text('Title', style: TextStyle(color: AppColors.primary, fontSize: 16.0, fontWeight: FontWeight.w400), textScaler: textScaler));
  }
}
