"""Figma clean-tree → Flutter flex wrap policy (constraints down, sizes up)."""

from figma_flutter_agent.generator.layout.flex_policy.wrap import (
    FlexWrapKind,
    resolve_flex_wrap,
    relax_row_cross_stretch_when_unbounded,
    hoist_flex_parent_data,
    apply_flex_wrap_to_widget,
    prepare_flex_child_extents,
    post_flex_layout_slot_extents,
    finalize_flex_child_extents,
    bind_row_cross_axis_height,
    _extract_balanced_prefix_child,
    _unwrap_flex_parent_data_wrapper,
    _outer_sized_box_head_has_infinite_height,
    _replace_infinite_height_literal,
    _row_loose_cross_axis_pin_already_applied,
    _row_cross_axis_pin_already_applied,
    _pin_row_cross_axis_height_inner,
    _bind_card_metadata_rail_width_only,
)

from figma_flutter_agent.generator.layout.flex_policy.row import (
    _row_hosts_horizontal_flex_children,
    row_is_tight_horizontal_chip,
    row_hosts_equal_metric_cards,
    row_equal_metric_cards_cross_axis,
    wrap_equal_metric_cards_row_height,
    row_is_numeric_counter_badge,
    row_is_space_between_text_metric_row,
    row_is_product_card_price_footer_row,
    row_is_icon_stepper_control_row,
    row_is_status_pill_badge,
    row_is_tight_horizontal_pill_label,
    row_is_toolbar_leading_title_row,
    row_hosts_chip_beside_heading,
    _row_title_column_should_expand_beside_chip,
    _row_child_looks_like_chip_host,
    _row_usable_main_span,
    _child_main_span,
    _row_child_keeps_intrinsic_width,
    _should_expand_sole_undersized_row_child,
    _row_hosts_title_text,
    _row_hosts_compact_icon_with_text,
    _row_hosts_stacked_column_peer,
    _parent_row_has_bounded_height,
    _column_peer_in_bounded_row,
    _resolve_row_cross_axis,
    row_is_card_composite_body,
    _row_hosts_stack_flow_column_peer,
)

from figma_flutter_agent.generator.layout.flex_policy.column import (
    column_is_oversized_photo_clip_host,
    _column_subtree_needs_cross_stretch,
    _column_is_text_primary,
    _column_prefers_min_height_pin,
    column_is_tight_stack_text_host,
    text_host_is_tight_positioned,
    column_in_bounded_positioned_host,
    column_child_should_center_hug,
    column_center_hug_child_wrap,
    column_is_product_card_footer_margin,
    column_is_product_tile_metadata,
    column_hosts_product_card_stepper,
    column_is_card_metadata_slot,
    column_bounded_slot_should_grow,
    column_bounded_slot_needs_vertical_scroll,
    column_cross_to_align_expr,
    _column_needs_expanded_under_row,
    _resolve_column_cross_axis,
    _is_form_field_group_column,
    _column_uses_loose_row_cross_axis_pin,
    _column_spaced_stack_sizes_intrinsically,
    wrap_column_child_width_fill,
    _coerce_column_cross_stretch_for_row_expand,
    _flex_column_open_index,
)

from figma_flutter_agent.generator.layout.flex_policy.stack import (
    stack_child_is_growable_panel,
    card_has_edge_to_edge_hero_stack,
    card_child_is_product_tile_metadata_slot,
    stack_is_card_metadata_host,
    stack_metadata_timestamp_host,
    stack_child_ordinal_top,
    stack_child_ordinal_bottom,
    stack_children_are_vertically_sequential,
    tree_children_are_vertically_sequential,
    _stack_is_title_subtitle_text_block,
    stack_should_flow_as_column,
    stack_child_is_pill_button,
    stack_child_ordinal_left,
    stack_pill_button_wrap_spacing,
    stack_should_flow_as_centered_wrap,
    _stack_flow_slot_prefers_min_height,
    stack_flow_child_horizontal_wrap,
    stack_flow_child_vertical_extent_wrap,
    _bound_stack_sized_box,
)

from figma_flutter_agent.generator.layout.flex_policy.buttons import (
    button_hosts_status_pill,
    horizontal_chip_button_should_hug_width,
    button_is_pill_with_centered_label,
    button_should_fitted_box_label,
    _bound_compact_icon_button,
)

from figma_flutter_agent.generator.layout.flex_policy.text import (
    text_in_card_metadata_rail,
    _text_has_multiple_lines,
    _subtree_has_input,
)

from figma_flutter_agent.generator.layout.flex_policy.alignment import (
    resolve_main_axis_alignment,
    resolve_cross_axis_alignment,
    emit_flexible_loose,
    _flex_child_should_bind_fixed_height,
    flex_host_prefers_min_height_pin,
)

__all__ = [
    # wrap
    "FlexWrapKind",
    "resolve_flex_wrap",
    "relax_row_cross_stretch_when_unbounded",
    "hoist_flex_parent_data",
    "apply_flex_wrap_to_widget",
    "prepare_flex_child_extents",
    "post_flex_layout_slot_extents",
    "finalize_flex_child_extents",
    "bind_row_cross_axis_height",
    "_extract_balanced_prefix_child",
    "_unwrap_flex_parent_data_wrapper",
    "_outer_sized_box_head_has_infinite_height",
    "_replace_infinite_height_literal",
    "_row_loose_cross_axis_pin_already_applied",
    "_row_cross_axis_pin_already_applied",
    "_pin_row_cross_axis_height_inner",
    "_bind_card_metadata_rail_width_only",
    # row
    "_row_hosts_horizontal_flex_children",
    "row_is_tight_horizontal_chip",
    "row_hosts_equal_metric_cards",
    "row_equal_metric_cards_cross_axis",
    "wrap_equal_metric_cards_row_height",
    "row_is_numeric_counter_badge",
    "row_is_space_between_text_metric_row",
    "row_is_product_card_price_footer_row",
    "row_is_icon_stepper_control_row",
    "row_is_status_pill_badge",
    "row_is_tight_horizontal_pill_label",
    "row_is_toolbar_leading_title_row",
    "row_hosts_chip_beside_heading",
    "_row_title_column_should_expand_beside_chip",
    "_row_child_looks_like_chip_host",
    "_row_usable_main_span",
    "_child_main_span",
    "_row_child_keeps_intrinsic_width",
    "_should_expand_sole_undersized_row_child",
    "_row_hosts_title_text",
    "_row_hosts_compact_icon_with_text",
    "_row_hosts_stacked_column_peer",
    "_parent_row_has_bounded_height",
    "_column_peer_in_bounded_row",
    "_resolve_row_cross_axis",
    "row_is_card_composite_body",
    "_row_hosts_stack_flow_column_peer",
    # column
    "column_is_oversized_photo_clip_host",
    "_column_subtree_needs_cross_stretch",
    "_column_is_text_primary",
    "_column_prefers_min_height_pin",
    "column_is_tight_stack_text_host",
    "text_host_is_tight_positioned",
    "column_in_bounded_positioned_host",
    "column_child_should_center_hug",
    "column_center_hug_child_wrap",
    "column_is_product_card_footer_margin",
    "column_is_product_tile_metadata",
    "column_hosts_product_card_stepper",
    "column_is_card_metadata_slot",
    "column_bounded_slot_should_grow",
    "column_bounded_slot_needs_vertical_scroll",
    "column_cross_to_align_expr",
    "_column_needs_expanded_under_row",
    "_resolve_column_cross_axis",
    "_is_form_field_group_column",
    "_column_uses_loose_row_cross_axis_pin",
    "_column_spaced_stack_sizes_intrinsically",
    "wrap_column_child_width_fill",
    "_coerce_column_cross_stretch_for_row_expand",
    "_flex_column_open_index",
    # stack
    "stack_child_is_growable_panel",
    "card_has_edge_to_edge_hero_stack",
    "card_child_is_product_tile_metadata_slot",
    "stack_is_card_metadata_host",
    "stack_metadata_timestamp_host",
    "stack_child_ordinal_top",
    "stack_child_ordinal_bottom",
    "stack_children_are_vertically_sequential",
    "tree_children_are_vertically_sequential",
    "_stack_is_title_subtitle_text_block",
    "stack_should_flow_as_column",
    "stack_child_is_pill_button",
    "stack_child_ordinal_left",
    "stack_pill_button_wrap_spacing",
    "stack_should_flow_as_centered_wrap",
    "_stack_flow_slot_prefers_min_height",
    "stack_flow_child_horizontal_wrap",
    "stack_flow_child_vertical_extent_wrap",
    "_bound_stack_sized_box",
    # buttons
    "button_hosts_status_pill",
    "horizontal_chip_button_should_hug_width",
    "button_is_pill_with_centered_label",
    "button_should_fitted_box_label",
    "_bound_compact_icon_button",
    # text
    "text_in_card_metadata_rail",
    "_text_has_multiple_lines",
    "_subtree_has_input",
    # alignment
    "resolve_main_axis_alignment",
    "resolve_cross_axis_alignment",
    "emit_flexible_loose",
    "_flex_child_should_bind_fixed_height",
    "flex_host_prefers_min_height_pin",
]
