"""Publish migration tests."""

from __future__ import annotations

from pathlib import Path

import pytest

from discord_bot.config.models import CustomCodePolicy
from discord_bot.db.enums import JobStatus
from discord_bot.db.store import GenerationJob
from discord_bot.publish.migrate import migrate_sandbox_to_repo


def _job(**kwargs) -> GenerationJob:
    base = dict(
        id="job1",
        run_id=None,
        figma_url="https://figma.test",
        discord_user_id=1,
        discord_channel_id=2,
        discord_message_id=None,
        review_message_id=None,
        project_dir="/tmp",
        feature_slug="bank_home",
        status=JobStatus.PREVIEW_READY,
        repo_key="mobile",
        git_provider="github",
        target_mode="existing",
        target_file_path="lib/features/bank_home/bank_home_screen.dart",
        fixed_preview_url=None,
        adaptive_preview_url=None,
        preview_token_hash=None,
        artifact_zip_path=None,
        artifact_repo_commit_url=None,
        gitlab_app_project_id=None,
        gitlab_issue_iid=None,
        gitlab_issue_url=None,
        gitlab_mr_iid=None,
        gitlab_mr_url=None,
        gitlab_source_branch=None,
        publish_branch=None,
        publish_pr_url=None,
        publish_pr_number=None,
        feedback_quality=None,
        feedback_comment=None,
        feedback_comment_message_id=None,
        issue_provider=None,
        issue_project_ref=None,
        issue_number=None,
        issue_url=None,
        issue_kind=None,
        error_message=None,
        created_at="",
        updated_at="",
    )
    base.update(kwargs)
    return GenerationJob(**base)


@pytest.mark.control_plane
def test_migrate_existing_screen_writes_target_path(tmp_path: Path) -> None:
    sandbox = tmp_path / "sandbox"
    repo = tmp_path / "repo"
    lib = sandbox / "lib" / "features" / "bank_home"
    lib.mkdir(parents=True)
    (lib / "bank_home_screen.dart").write_text(
        "// <auto-generated>\ngenerated\n// </auto-generated>\n",
        encoding="utf-8",
    )
    job = _job(target_file_path="lib/features/bank_home/bank_home_screen.dart")
    files = migrate_sandbox_to_repo(
        sandbox_dir=sandbox,
        repo_dir=repo,
        job=job,
        custom_code_policy=CustomCodePolicy.PRESERVE_CUSTOM,
    )
    target = repo / "lib/features/bank_home/bank_home_screen.dart"
    assert target.is_file()
    assert "lib/features/bank_home/bank_home_screen.dart" in files
