"""Assemble screen, layout, and widget Dart into a single debug bundle file."""

from __future__ import annotations

import re
from pathlib import Path
from typing import Literal

from loguru import logger

from figma_flutter_agent.debug.dart_bundle_parse import (
    _IMPORT_RE,
)
from figma_flutter_agent.debug.paths import dart_debug_snapshot_path
from figma_flutter_agent.generator.paths import Architecture, screen_file_path

DartDebugSnapshot = Literal["plan", "final", "bug"]

_SKIP_HEADER_RE = re.compile(
    r"^//\s*(<auto-generated>|</auto-generated>|Generated by figma-flutter-agent|<custom-code>|</custom-code>)",
)


def _uri_to_lib_path(uri: str, *, package_name: str) -> str | None:
    prefix = f"package:{package_name}/"
    if uri.startswith(prefix):
        return f"lib/{uri.removeprefix(prefix)}"
    return None


def _collect_import_uris(source: str) -> list[str]:
    return [match.group("uri") for match in _IMPORT_RE.finditer(source)]


def _collect_bundle_paths(
    *,
    screen_path: str,
    planned_files: dict[str, str],
    package_name: str,
) -> tuple[list[str], list[str]]:
    """Return widget/layout paths to inline and the screen path."""
    pending = [screen_path]
    seen: set[str] = set()
    widget_paths: list[str] = []
    layout_paths: list[str] = []

    while pending:
        path = pending.pop(0)
        if path in seen:
            continue
        seen.add(path)
        source = planned_files.get(path)
        if source is None:
            continue
        for uri in _collect_import_uris(source):
            lib_path = _uri_to_lib_path(uri, package_name=package_name)
            if lib_path is None or lib_path not in planned_files:
                continue
            if lib_path.startswith("lib/widgets/"):
                if lib_path not in widget_paths:
                    widget_paths.append(lib_path)
                pending.append(lib_path)
            elif lib_path.startswith("lib/generated/") and lib_path.endswith("_layout.dart"):
                if lib_path not in layout_paths:
                    layout_paths.append(lib_path)
                pending.append(lib_path)

    widget_paths.sort()
    layout_paths.sort()
    return widget_paths, layout_paths


def _collect_external_imports(
    paths: list[str],
    planned_files: dict[str, str],
    *,
    inlined_paths: set[str],
    package_name: str,
) -> list[str]:
    imports: list[str] = []
    seen: set[str] = set()
    for path in paths:
        source = planned_files.get(path, "")
        for uri in _collect_import_uris(source):
            lib_path = _uri_to_lib_path(uri, package_name=package_name)
            if lib_path in inlined_paths:
                continue
            if uri in seen:
                continue
            seen.add(uri)
            imports.append(f"import '{uri}';")
    return imports


def _strip_file_preamble(source: str) -> str:
    lines: list[str] = []
    for line in source.splitlines():
        stripped = line.strip()
        if not stripped:
            if lines and lines[-1] != "":
                lines.append("")
            continue
        if _IMPORT_RE.match(stripped):
            continue
        if _SKIP_HEADER_RE.match(stripped):
            continue
        if stripped == "// Do not edit by hand.":
            continue
        lines.append(line)
    while lines and lines[0] == "":
        lines.pop(0)
    while lines and lines[-1] == "":
        lines.pop()
    return "\n".join(lines)


def build_planned_dart_bundle(
    *,
    feature_name: str,
    planned_files: dict[str, str],
    package_name: str,
    architecture: Architecture = "feature_first",
    banner: str = "DEBUG BUNDLE",
    description: str = (
        "Single-file view of screen + inlined widgets/layout from this generation run."
    ),
    pipeline_run_id: str | None = None,
) -> str | None:
    """Build a single-file Dart bundle from planned project files.

    Args:
        feature_name: Resolved screen feature slug.
        planned_files: Planned project files keyed by relative path.
        package_name: Flutter package name from ``pubspec.yaml``.
        architecture: Project layout mode.
        banner: First-line bundle label (e.g. ``DEBUG BUNDLE``, ``EMITTER REFERENCE``).
        description: Human-readable bundle purpose comment.
        pipeline_run_id: Optional run id stamped for Run Gate served probe.

    Returns:
        Bundled Dart source, or ``None`` when the screen file is missing.
    """
    screen_path = screen_file_path(feature_name, architecture=architecture)
    screen_source = planned_files.get(screen_path)
    if screen_source is None:
        return None

    widget_paths, layout_paths = _collect_bundle_paths(
        screen_path=screen_path,
        planned_files=planned_files,
        package_name=package_name,
    )
    inlined_paths = set(widget_paths) | set(layout_paths)
    ordered_paths = [*widget_paths, *layout_paths, screen_path]
    imports = _collect_external_imports(
        ordered_paths,
        planned_files,
        inlined_paths=inlined_paths,
        package_name=package_name,
    )

    sections: list[str] = [
        f"// {banner} — not for compilation.",
        f"// Feature: {feature_name}",
        f"// {description}",
        "// Generated by figma-flutter-agent.",
    ]
    if pipeline_run_id:
        sections.append(f"// FFA_RUN_ID: {pipeline_run_id}")
    sections.extend(["", *imports, ""])

    for path in ordered_paths:
        body = _strip_file_preamble(planned_files.get(path, ""))
        if not body:
            continue
        from figma_flutter_agent.generator.dart.project_validation.minified_expand import (
            expand_minified_dart_source_for_readability,
        )

        body = expand_minified_dart_source_for_readability(body)
        sections.extend(
            [
                f"// --- begin {path} ---",
                body,
                f"// --- end {path} ---",
                "",
            ]
        )

    return "\n".join(sections).rstrip() + "\n"


def build_dart_debug_bundle(
    *,
    feature_name: str,
    planned_files: dict[str, str],
    package_name: str,
    architecture: Architecture = "feature_first",
    pipeline_run_id: str | None = None,
) -> str | None:
    """Build a single-file Dart bundle for screen debugging.

    Args:
        feature_name: Resolved screen feature slug.
        planned_files: Final planned project files keyed by relative path.
        package_name: Flutter package name from ``pubspec.yaml``.
        architecture: Project layout mode.

    Returns:
        Bundled Dart source, or ``None`` when the screen file is missing.
    """
    return build_planned_dart_bundle(
        feature_name=feature_name,
        planned_files=planned_files,
        package_name=package_name,
        architecture=architecture,
        pipeline_run_id=pipeline_run_id,
    )


def write_dart_debug_snapshot(
    project_dir: Path,
    *,
    feature_name: str,
    planned_files: dict[str, str],
    package_name: str,
    architecture: Architecture = "feature_first",
    snapshot: DartDebugSnapshot = "final",
    pipeline_run_id: str | None = None,
) -> Path | None:
    """Write a debug Dart bundle snapshot for ``feature_name``.

    Args:
        project_dir: Flutter project root.
        feature_name: Resolved screen feature slug.
        planned_files: Planned project files keyed by relative path.
        package_name: Flutter package name from ``pubspec.yaml``.
        architecture: Project layout mode.
        snapshot: ``plan`` after plan stage, ``final`` before write, ``bug`` on gate failure.
        pipeline_run_id: Optional run id for ``FFA_RUN_ID`` stamp in the debug bundle.

    Returns:
        Path to the written bundle, or ``None`` when the screen is missing.
    """
    bundle = build_dart_debug_bundle(
        feature_name=feature_name,
        planned_files=planned_files,
        package_name=package_name,
        architecture=architecture,
        pipeline_run_id=pipeline_run_id,
    )
    if bundle is None:
        return None
    path = dart_debug_snapshot_path(project_dir, feature_name, snapshot)
    path.parent.mkdir(parents=True, exist_ok=True)
    header = f"// Snapshot: {snapshot}\n" if snapshot != "final" else ""
    path.write_text(header + bundle, encoding="utf-8")
    logger.info("Saved debug Dart snapshot ({}) to {}", snapshot, path.as_posix())
    return path


def write_dart_debug_bundle(
    project_dir: Path,
    *,
    feature_name: str,
    planned_files: dict[str, str],
    package_name: str,
    architecture: Architecture = "feature_first",
) -> Path | None:
    """Write the final pre-write debug Dart bundle for ``feature_name``."""
    return write_dart_debug_snapshot(
        project_dir,
        feature_name=feature_name,
        planned_files=planned_files,
        package_name=package_name,
        architecture=architecture,
        snapshot="final",
    )
