"""Parse debug Dart bundles back into planned files."""

from __future__ import annotations

import re

from figma_flutter_agent.generator.paths import Architecture, screen_file_path

_IMPORT_RE = re.compile(r"^import\s+['\"](?P<uri>[^'\"]+)['\"]\s*;\s*$", re.MULTILINE)
_SECTION_BEGIN_RE = re.compile(r"^// --- begin (?P<path>.+?) ---\s*$", re.MULTILINE)
_CLASS_RE = re.compile(r"^class (\w+)", re.MULTILINE)
_SCREEN_SHELL_CLASSES = frozenset({"GeneratedScreenShell"})


def parse_planned_dart_bundle(source: str) -> tuple[list[str], dict[str, str]]:
    """Parse a single-file debug bundle back into per-file bodies."""
    lines = source.splitlines()
    while lines and lines[0].startswith("// Snapshot:"):
        lines.pop(0)
    text = "\n".join(lines)
    first_section = _SECTION_BEGIN_RE.search(text)
    header = text[: first_section.start()] if first_section else text
    external_imports = [
        line
        for line in header.splitlines()
        if _IMPORT_RE.match(line.strip())
    ]
    sections: dict[str, str] = {}
    for match in _SECTION_BEGIN_RE.finditer(text):
        path = match.group("path").strip()
        start = match.end() + 1
        end_marker = f"// --- end {path} ---"
        end_idx = text.find(end_marker, start)
        body = text[start:end_idx] if end_idx >= 0 else text[start:]
        sections[path] = body.strip()
    return external_imports, sections


def planned_files_from_dart_bundle(
    source: str,
    *,
    package_name: str,
) -> dict[str, str]:
    """Rebuild planned project files from a debug/reference Dart bundle."""
    external_imports, sections = parse_planned_dart_bundle(source)
    if not sections:
        msg = "Debug bundle contains no // --- begin lib/... --- sections."
        raise ValueError(msg)

    def _bundle_section_order(path: str) -> tuple[int, str]:
        if path.startswith("lib/widgets/"):
            return (0, path)
        if path.startswith("lib/generated/"):
            return (1, path)
        return (2, path)

    ordered_paths = sorted(sections, key=_bundle_section_order)
    planned: dict[str, str] = {}
    prior: list[tuple[str, str]] = []
    for path in ordered_paths:
        body = sections[path]
        imports = list(external_imports)
        seen = set(imports)
        for prior_path, prior_body in prior:
            if not _section_references_prior(body, prior_body):
                continue
            uri = f"package:{package_name}/{prior_path.removeprefix('lib/')}"
            import_line = f"import '{uri}';"
            if import_line not in seen:
                seen.add(import_line)
                imports.append(import_line)
        preamble = [
            "// <auto-generated>",
            "// Do not edit by hand.",
            "",
            *imports,
        ]
        if imports:
            preamble.append("")
        planned[path] = "\n".join([*preamble, body, ""])
        prior.append((path, body))
    return planned


def detect_screen_class_from_planned_files(
    planned_files: dict[str, str],
    *,
    feature_name: str,
    architecture: Architecture = "feature_first",
) -> str:
    """Return the primary screen widget class from planned files."""
    from figma_flutter_agent.parser.navigation import _screen_class_name

    screen_path = screen_file_path(feature_name, architecture=architecture)
    screen_source = planned_files.get(screen_path, "")
    expected = _screen_class_name(feature_name)
    declared = _CLASS_RE.findall(screen_source)
    if expected in declared:
        return expected
    for class_name in declared:
        if class_name in _SCREEN_SHELL_CLASSES:
            continue
        if class_name.endswith("Screen"):
            return class_name
    return expected


def _section_references_prior(body: str, prior_body: str) -> bool:
    for class_name in _CLASS_RE.findall(prior_body):
        if re.search(rf"\b{re.escape(class_name)}\b", body):
            return True
    return False
