"""Split generated Dart into import header and widget body; keep directives at the top."""

from __future__ import annotations

import re

_DIRECTIVE_LINE_RE = re.compile(r"^\s*(?:import|export|part)\s+")
_AUTO_GENERATED_OPEN_RE = re.compile(
    r"^\s*//\s*<auto-generated>\s*$",
    re.IGNORECASE,
)


def strip_directives_from_fragment(source: str) -> str:
    """Remove ``import``/``export``/``part`` lines from a screen or widget body fragment."""
    kept: list[str] = []
    for line in source.splitlines():
        if line.strip() and _DIRECTIVE_LINE_RE.match(line):
            continue
        kept.append(line)
    return "\n".join(kept)


def collect_directive_lines(source: str) -> list[str]:
    seen: set[str] = set()
    directives: list[str] = []
    for line in source.splitlines():
        stripped = line.strip()
        if not stripped or not _DIRECTIVE_LINE_RE.match(line):
            continue
        if stripped in seen:
            continue
        seen.add(stripped)
        directives.append(stripped)
    return directives


def _header_insert_index(lines: list[str]) -> int:
    index = 0
    while index < len(lines):
        stripped = lines[index].strip()
        if not stripped:
            index += 1
            continue
        if _AUTO_GENERATED_OPEN_RE.match(stripped):
            index += 1
            while index < len(lines):
                inner = lines[index].strip()
                if re.match(
                    r"^\s*//\s*</auto-generated>\s*$",
                    lines[index],
                    re.IGNORECASE,
                ):
                    index += 1
                    break
                if inner and not inner.startswith("//"):
                    break
                index += 1
            continue
        if re.match(r"^\s*//\s*<(?!(?:/?custom-code)\b)[^>]+>\s*$", stripped):
            index += 1
            continue
        if _DIRECTIVE_LINE_RE.match(lines[index]):
            index += 1
            continue
        break
    return index


def relocate_directives_to_header(source: str) -> str:
    """Hoist stray ``import``/``export`` lines into the file header import block."""
    directives = collect_directive_lines(source)
    body = strip_directives_from_fragment(source)
    if not directives:
        return body
    lines = body.splitlines()
    insert_at = _header_insert_index(lines)
    existing = {line.strip() for line in lines if _DIRECTIVE_LINE_RE.match(line)}
    to_insert = [line for line in directives if line not in existing]
    if not to_insert:
        return body
    block = to_insert + [""] if insert_at < len(lines) and lines[insert_at].strip() else to_insert
    merged = lines[:insert_at] + block + lines[insert_at:]
    return "\n".join(merged)
