"""Custom-code preservation criterion for spec-23."""

from __future__ import annotations

import tempfile
from pathlib import Path

from figma_flutter_agent.generator.writing.core import DartWriter
from figma_flutter_agent.generator.writing.custom_code import merge_custom_code
from figma_flutter_agent.validation.spec23.models import Spec23CriterionResult


def _criterion_developer_changes_preserved(*, strict: bool) -> Spec23CriterionResult:
    existing = (
        "// <auto-generated>\n"
        "class GeneratedScreen extends StatelessWidget {\n"
        "  const GeneratedScreen({super.key});\n"
        "}\n"
        "// </auto-generated>\n\n"
        "// <custom-code>\nfinal customFlag = true;\n// </custom-code>\n"
    )
    regenerated = (
        "// <auto-generated>\n"
        "class GeneratedScreen extends StatelessWidget {\n"
        "  const GeneratedScreen({super.key});\n"
        "}\n"
        "// </auto-generated>\n\n"
        "// <custom-code>\n// </custom-code>\n"
    )
    target = "lib/features/demo/demo_screen.dart"

    if not strict:
        merged = merge_custom_code(regenerated, existing)
        passed = "final customFlag = true;" in merged
        return Spec23CriterionResult(
            name="developer_changes_preserved",
            passed=passed,
            detail="merge_custom_code",
        )

    with tempfile.TemporaryDirectory() as tmp_dir:
        project_dir = Path(tmp_dir)
        (project_dir / "pubspec.yaml").write_text("name: demo_app\n", encoding="utf-8")
        writer = DartWriter(project_dir, enable_backup=False)
        writer.write_files({target: existing})
        writer.write_files({target: regenerated})
        written = (project_dir / target).read_text(encoding="utf-8")
    passed = "final customFlag = true;" in written
    return Spec23CriterionResult(
        name="developer_changes_preserved",
        passed=passed,
        detail="DartWriter regen",
    )
