"""Reusable widget Dart file assembly."""

from __future__ import annotations

from figma_flutter_agent.generator.layout.file_preamble import (
    build_scaler_preamble,
    dart_ui_import_line,
)
from figma_flutter_agent.generator.layout.interactive_chrome import (
    ensure_interactive_layout_helpers,
)
from figma_flutter_agent.generator.layout.navigation.helpers import (
    bottom_nav_stateful_helpers,
    icon_nav_stateful_helpers,
    pill_nav_stateful_helpers,
)
from figma_flutter_agent.generator.paths import ImportContext


def render_widget_file(
    *,
    class_name: str,
    body: str,
    uses_svg: bool,
    package_name: str = "demo_app",
    use_package_imports: bool = True,
    source_file: str = "lib/widgets/widget.dart",
    widget_fields: str = "",
    constructor_params: str = "{super.key}",
) -> str:
    """Render a reusable widget Dart file body."""
    import_context = ImportContext(
        package_name=package_name,
        use_package_imports=use_package_imports,
        source_file=source_file,
    )
    svg_import = ""
    if uses_svg and "SvgPicture" in body:
        svg_import = "import 'package:flutter_svg/flutter_svg.dart';\n"
    colors_import = ""
    if "AppColors" in body:
        colors_import = f"import '{import_context.uri('theme/app_colors.dart')}';\n"
    spacing_import = ""
    if "AppSpacing" in body:
        spacing_import = f"import '{import_context.uri('theme/app_spacing.dart')}';\n"
    elevation_import = ""
    if "AppElevation" in body:
        elevation_import = f"import '{import_context.uri('theme/app_elevation.dart')}';\n"
    needs_layout_import = (
        "AppBreakpoints" in body
        or "_LayoutChromeNav(" in body
        or "_LayoutPillNav(" in body
        or "_LayoutIconNav(" in body
    )
    layout_import = ""
    if needs_layout_import:
        layout_import = f"import '{import_context.uri('theme/app_layout.dart')}';\n"
    widget_helpers = ""
    if "_LayoutPillNav(" in body and "class _LayoutPillNav extends StatefulWidget" not in body:
        widget_helpers = pill_nav_stateful_helpers(node_id="widget-bottom-nav")
    elif "_LayoutIconNav(" in body and "class _LayoutIconNav extends StatefulWidget" not in body:
        widget_helpers = icon_nav_stateful_helpers(node_id="widget-bottom-nav")
    elif (
        "_LayoutChromeNav(" in body and "class _LayoutChromeNav extends StatefulWidget" not in body
    ):
        nav_id = "widget-bottom-nav"
        widget_helpers = bottom_nav_stateful_helpers(
            theme_variant="material_3",
            node_id=nav_id,
        )
    from figma_flutter_agent.generator.layout.common import (
        ARTBOARD_PREVIEW_CLASS_FIELDS,
        ARTBOARD_PREVIEW_LAYOUT_MARKER,
    )

    scaler_preamble = build_scaler_preamble(body)
    dart_ui_import = dart_ui_import_line(body)
    cupertino_import = ""
    if "CupertinoPicker" in body:
        cupertino_import = "import 'package:flutter/cupertino.dart';\n"
    artboard_preview_fields = (
        ARTBOARD_PREVIEW_CLASS_FIELDS if ARTBOARD_PREVIEW_LAYOUT_MARKER in body else ""
    )
    rendered = f"""// <auto-generated>
// Generated by figma-flutter-agent. Do not edit by hand.
// </auto-generated>

import 'package:flutter/material.dart';
{dart_ui_import}{cupertino_import}{svg_import}{colors_import}{spacing_import}{layout_import}{elevation_import}// <custom-code>
// </custom-code>
{widget_helpers}
class {class_name} extends StatelessWidget {{
{artboard_preview_fields}{widget_fields}  const {class_name}({constructor_params});

  @override
  Widget build(BuildContext context) {{
{scaler_preamble}    return {body};
  }}
}}
"""
    return ensure_interactive_layout_helpers(rendered)
