"""Custom-code preservation zones for generated files."""

from __future__ import annotations

import re

_CUSTOM_CODE_BLOCK_RE = re.compile(
    r"//\s*<\s*custom-code(?:\s*:\s*(?P<name>[\w.:+-]+))?\s*>\s*\n?"
    r"(?P<body>.*?)"
    r"//\s*</\s*custom-code(?:\s*:\s*(?P=name))?\s*>",
    re.DOTALL | re.IGNORECASE,
)
_AUTO_GENERATED_BLOCK_RE = re.compile(
    r"// <auto-generated>.*?// </auto-generated>",
    re.DOTALL,
)
_ORPHAN_NOISE_LINE_RE = re.compile(r"^[\s\)\}]+$")
_AGENT_GENERATED_BANNER = "// Generated by figma-flutter-agent"


def format_orphan_edit_message(
    relative_path: str,
    content: str,
    orphan_lines: list[int],
    *,
    max_lines: int = 3,
) -> str:
    """Build a human-readable message for edits outside preservation zones."""
    line_list = content.splitlines()
    previews: list[str] = []
    for line_no in orphan_lines[:max_lines]:
        if 1 <= line_no <= len(line_list):
            snippet = line_list[line_no - 1].strip()
            if len(snippet) > 72:
                snippet = f"{snippet[:69]}..."
            previews.append(f"L{line_no}: {snippet}")
    preview_suffix = f" Preview: {' | '.join(previews)}" if previews else ""
    numbers = ", ".join(str(line) for line in orphan_lines[:8])
    suffix = "..." if len(orphan_lines) > 8 else ""
    return (
        f"Manual edits outside preservation zones in {relative_path} "
        f"(lines: {numbers}{suffix}).{preview_suffix}"
    )


def find_orphan_line_numbers(content: str) -> list[int]:
    """Return 1-based line numbers with user code outside preservation zones."""
    if _AGENT_GENERATED_BANNER in content:
        return []

    protected = _protected_line_numbers(content)
    orphans: list[int] = []
    for line_no, line in enumerate(content.splitlines(), start=1):
        stripped = line.strip()
        if not stripped or stripped.startswith("//"):
            continue
        if _ORPHAN_NOISE_LINE_RE.match(stripped):
            continue
        if line_no not in protected:
            orphans.append(line_no)
    return orphans


def extract_custom_code_blocks_ordered(content: str) -> list[tuple[str, str]] | None:
    """Extract custom-code blocks in source order as ``(zone_name, body)`` pairs."""
    matches = list(_CUSTOM_CODE_BLOCK_RE.finditer(content))
    if not matches:
        return None
    return [(match.group("name") or "", match.group("body").strip("\n")) for match in matches]


def extract_custom_code_blocks(content: str) -> dict[str, str] | None:
    """Extract all custom-code blocks keyed by zone name."""
    ordered = extract_custom_code_blocks_ordered(content)
    if ordered is None:
        return None
    blocks: dict[str, str] = {}
    for name, body in ordered:
        blocks[name] = body
    return blocks


def extract_custom_code(content: str) -> str | None:
    """Extract user code from the legacy unnamed custom-code block."""
    blocks = extract_custom_code_blocks(content)
    if blocks is None:
        return None
    return blocks.get("", next(iter(blocks.values()), ""))


def merge_custom_code(new_content: str, existing_content: str) -> str:
    """Preserve existing custom-code blocks inside newly generated content."""
    preserved = extract_custom_code_blocks_ordered(existing_content)
    if preserved is None:
        return new_content

    if _CUSTOM_CODE_BLOCK_RE.search(new_content) is None:
        notes = _format_unmerged_blocks({name: body for name, body in preserved})
        return _insert_after_imports(new_content, notes) if notes else new_content

    from figma_flutter_agent.generator.custom_code_zones import (
        is_legacy_role_zone,
        legacy_role_from_zone,
    )

    preserved_by_name: dict[str, str] = {}
    legacy_role_bodies: dict[str, str] = {}
    positional_bodies: list[str] = []
    for name, body in preserved:
        preserved_by_name[name] = body
        positional_bodies.append(body)
        role = legacy_role_from_zone(name)
        if role is not None:
            legacy_role_bodies.setdefault(role, body)
        elif is_legacy_role_zone(name):
            legacy_role_bodies.setdefault(name, body)

    index = 0

    def replace(match: re.Match[str]) -> str:
        nonlocal index
        name = match.group("name") or ""
        body = _preserved_body_for_zone(name, preserved_by_name, legacy_role_bodies)
        if not body.strip() and index < len(positional_bodies):
            body = positional_bodies[index]
        if index < len(positional_bodies):
            index += 1
        open_marker = _custom_code_marker(name)
        close_marker = _custom_code_marker(name, closing=True)
        if body.strip():
            zone_indent = _custom_code_zone_indent(new_content, match)
            body = _rebase_custom_code_indent(body, zone_indent)
        inner = f"\n{body}\n" if body.strip() else "\n"
        return f"{open_marker}{inner}{close_marker}"

    merged = _CUSTOM_CODE_BLOCK_RE.sub(replace, new_content)
    unmatched = positional_bodies[index:]
    notes = _format_unmerged_blocks(
        {f"preserved-{idx}": body for idx, body in enumerate(unmatched, start=1)}
    )
    if notes:
        merged = _insert_after_imports(merged, notes)
    return merged


def _protected_line_numbers(content: str) -> set[int]:
    """Line numbers inside ``<auto-generated>`` or ``<custom-code>`` markers."""
    protected: set[int] = set()
    for pattern in (_AUTO_GENERATED_BLOCK_RE, _CUSTOM_CODE_BLOCK_RE):
        for match in pattern.finditer(content):
            start = content.count("\n", 0, match.start()) + 1
            end = content.count("\n", 0, match.end()) + 1
            protected.update(range(start, end + 1))
    return protected


def _custom_code_marker(name: str, *, closing: bool = False) -> str:
    suffix = f":{name}" if name else ""
    prefix = "/" if closing else ""
    return f"// <{prefix}custom-code{suffix}>"


def _leading_indent(line: str) -> str:
    return line[: len(line) - len(line.lstrip(" \t"))]


def _rebase_custom_code_indent(body: str, target_indent: str) -> str:
    """Shift preserved custom code so it aligns with the new file's zone indentation."""
    lines = body.splitlines()
    non_empty = [line for line in lines if line.strip()]
    if not non_empty:
        return body
    base_len = min(len(_leading_indent(line)) for line in non_empty)
    rebased: list[str] = []
    for line in lines:
        if not line.strip():
            rebased.append("")
            continue
        content = line[base_len:] if len(line) >= base_len else line.lstrip()
        rebased.append(f"{target_indent}{content}")
    return "\n".join(rebased)


def _custom_code_zone_indent(content: str, match: re.Match[str]) -> str:
    """Return indentation for lines inside a custom-code zone."""
    line_start = content.rfind("\n", 0, match.start()) + 1
    line_end = content.find("\n", match.start())
    if line_end == -1:
        line_end = len(content)
    marker_line = content[line_start:line_end]
    return f"{_leading_indent(marker_line)}  "


def _insert_after_imports(content: str, block: str) -> str:
    """Insert a block after the last import/export line to preserve Dart import order."""
    if not block.strip():
        return content
    lines = content.splitlines()
    last_import = -1
    for index, line in enumerate(lines):
        stripped = line.strip()
        if stripped.startswith("import ") or stripped.startswith("export "):
            last_import = index
    if last_import < 0:
        return f"{block}\n{content}" if content else block
    head = lines[: last_import + 1]
    tail = lines[last_import + 1 :]
    return "\n".join([*head, "", block, "", *tail])


def _preserved_body_for_zone(
    zone_name: str,
    preserved_by_name: dict[str, str],
    legacy_role_bodies: dict[str, str],
) -> str:
    """Resolve preserved user code for a newly generated zone name."""
    if zone_name in preserved_by_name:
        return preserved_by_name[zone_name]
    from figma_flutter_agent.generator.custom_code_zones import legacy_role_from_zone

    role = legacy_role_from_zone(zone_name)
    if role is not None and role in legacy_role_bodies:
        return legacy_role_bodies[role]
    if role is not None:
        for key, body in preserved_by_name.items():
            if legacy_role_from_zone(key) == role:
                return body
    return ""


def _format_unmerged_blocks(blocks: dict[str, str]) -> str:
    """Serialize unmatched custom-code zones so user logic is never dropped."""
    if not blocks:
        return ""
    sections: list[str] = []
    for name, body in blocks.items():
        open_marker = _custom_code_marker(name)
        close_marker = _custom_code_marker(name, closing=True)
        inner = f"\n{body}\n" if body.strip() else "\n"
        sections.append(f"{open_marker}{inner}{close_marker}")
    return "\n\n".join(sections)
