// <auto-generated>
// Generated by figma-flutter-agent. Do not edit by hand.
// </auto-generated>

import 'package:flutter/material.dart';

import 'app_colors.dart';
import 'app_layout.dart';
import 'app_typography.dart';

// <custom-code>
// </custom-code>

class AppTheme {
  AppTheme._();

  static TextTheme _buildTextTheme() {
    return const TextTheme(
      displayLarge: AppTypography.title,
      headlineLarge: AppTypography.tContinue,
    );
  }

  static ThemeData light({double maxWebWidth = 1200}) {
    return ThemeData(
      useMaterial3: true,
      colorScheme: ColorScheme.fromSeed(
        seedColor: AppColors.primary,
        brightness: Brightness.light,
      ),
      textTheme: _buildTextTheme(),
      extensions: <ThemeExtension<dynamic>>[
        AppLayoutExtension(maxWebWidth: maxWebWidth),
      ],
    );
  }

}
