// <auto-generated>
// Generated by figma-flutter-agent. Do not edit by hand.
// </auto-generated>

// <custom-code>
// </custom-code>

class AppSpacing {
  AppSpacing._();

  static const double md = 12.0;
}
