// <auto-generated>
// Generated by figma-flutter-agent. Do not edit by hand.
// </auto-generated>

import 'package:flutter/material.dart';

// <custom-code>
// </custom-code>

class AppEdgeInsets {
  AppEdgeInsets._();

  static const EdgeInsets md = EdgeInsets.fromLTRB(
    16.0,
    12.0,
    16.0,
    12.0,
  );
  static const EdgeInsets inset1 = EdgeInsets.fromLTRB(
    16.0,
    16.0,
    16.0,
    16.0,
  );
}
