"""Shared navigation emit constants."""

from __future__ import annotations

MIN_BOTTOM_NAV_ITEMS = 2
MAX_BOTTOM_NAV_ITEMS = 7
MAX_BOTTOM_NAV_HOST_HEIGHT = 160.0
COMPACT_ICON_NAV_TAB_MAX = 36.0
PILL_NAV_MIN_WIDTH = 60.0
PILL_NAV_MAX_WIDTH = 96.0
PILL_NAV_MIN_HEIGHT = 32.0
PILL_NAV_MAX_HEIGHT = 40.0
NAV_SHELL_MIN_WIDTH = 300.0
TOP_NAV_BACK_AFFORDANCE_MAX_LEFT = 48.0
TOP_NAV_TRAILING_AFFORDANCE_MIN_CENTER_RATIO = 0.65
