"""Layout file assembly and deterministic screen shells."""

from __future__ import annotations

from figma_flutter_agent.generator.cluster_variants import ClusterVectorVariant
from figma_flutter_agent.generator.layout_navigation import (
    bottom_nav_stateful_helpers,
    tree_contains_node_type,
)
from figma_flutter_agent.generator.layout_widget import render_node_body
from figma_flutter_agent.generator.paths import Architecture, ImportContext
from figma_flutter_agent.generator.renderer import DartRenderer, to_pascal_case
from figma_flutter_agent.schemas import CleanDesignTreeNode, FlutterGenerationResponse, NodeType

__all__ = [
    "render_deterministic_screen_files",
    "render_layout_file",
    "render_node_body",
    "render_widget_file",
]


def render_widget_file(
    *,
    class_name: str,
    body: str,
    uses_svg: bool,
    package_name: str = "demo_app",
    use_package_imports: bool = True,
    source_file: str = "lib/widgets/widget.dart",
    widget_fields: str = "",
    constructor_params: str = "{super.key}",
) -> str:
    """Render a reusable widget Dart file body."""
    import_context = ImportContext(
        package_name=package_name,
        use_package_imports=use_package_imports,
        source_file=source_file,
    )
    svg_import = "import 'package:flutter_svg/flutter_svg.dart';\n" if uses_svg else ""
    elevation_import = ""
    if "AppElevation" in body:
        elevation_import = f"import '{import_context.uri('theme/app_elevation.dart')}';\n"
    return f"""// <auto-generated>
// Generated by figma-flutter-agent. Do not edit by hand.
// </auto-generated>

import 'package:flutter/material.dart';
{svg_import}
import '{import_context.uri("theme/app_colors.dart")}';
import '{import_context.uri("theme/app_spacing.dart")}';
{elevation_import}
// <custom-code>
// </custom-code>

class {class_name} extends StatelessWidget {{
{widget_fields}  const {class_name}({constructor_params});

  @override
  Widget build(BuildContext context) {{
    final textScaler = MediaQuery.textScalerOf(context);
    return {body};
  }}
}}
"""


def render_layout_file(
    tree: CleanDesignTreeNode,
    *,
    feature_name: str,
    uses_svg: bool,
    cluster_classes: dict[str, str] | None = None,
    cluster_vector_variants: dict[str, ClusterVectorVariant] | None = None,
    widget_imports: list[str] | None = None,
    package_name: str = "demo_app",
    use_package_imports: bool = True,
    theme_variant: str = "material_3",
    responsive_enabled: bool = True,
    bundled_font_families: frozenset[str] | None = None,
    dart_weight_overrides_by_family: dict[str, dict[str, str]] | None = None,
) -> dict[str, str]:
    """Render deterministic layout Dart for a clean design tree."""
    class_name = f"{to_pascal_case(feature_name)}Layout"
    layout_widget = render_node_body(
        tree,
        uses_svg=uses_svg,
        cluster_classes=cluster_classes,
        cluster_vector_variants=cluster_vector_variants,
        theme_variant=theme_variant,
        responsive_enabled=responsive_enabled,
        is_layout_root=True,
        bundled_font_families=bundled_font_families,
        dart_weight_overrides_by_family=dart_weight_overrides_by_family,
    )
    cupertino_import = (
        "import 'package:flutter/cupertino.dart';\n\n" if theme_variant == "cupertino" else ""
    )
    svg_import = "import 'package:flutter_svg/flutter_svg.dart';\n\n" if uses_svg else ""
    layout_path = f"lib/generated/{feature_name}_layout.dart"
    import_context = ImportContext(
        package_name=package_name,
        use_package_imports=use_package_imports,
        source_file=layout_path,
    )
    widget_import_lines = ""
    if widget_imports:
        widget_import_lines = "".join(
            f"import '{import_context.uri(f'widgets/{file_name}.dart')}';\n"
            for file_name in sorted(set(widget_imports))
        )
        if widget_import_lines:
            widget_import_lines += "\n"
    bottom_nav_helpers = ""
    if tree_contains_node_type(tree, NodeType.BOTTOM_NAV):
        bottom_nav_helpers = f"{bottom_nav_stateful_helpers()}\n"
    layout_import = ""
    if responsive_enabled:
        layout_import = f"import '{import_context.uri('theme/app_layout.dart')}';\n"
    content = f"""// <auto-generated>
// Generated by figma-flutter-agent. Do not edit by hand.
// </auto-generated>

import 'package:flutter/material.dart';
import 'package:flutter/gestures.dart';

{cupertino_import}{svg_import}import '{import_context.uri("theme/app_colors.dart")}';
import '{import_context.uri("theme/app_spacing.dart")}';
import '{import_context.uri("theme/app_elevation.dart")}';
{layout_import}{widget_import_lines}// <custom-code>
// </custom-code>
{bottom_nav_helpers}
/// Deterministic layout generated from the Figma clean design tree.
class {class_name} extends StatelessWidget {{
  const {class_name}({{super.key}});

  @override
  Widget build(BuildContext context) {{
    final textScaler = MediaQuery.textScalerOf(context);
    return {layout_widget};
  }}
}}
"""
    return {f"lib/generated/{feature_name}_layout.dart": content}


def _screen_app_bar_title(feature_name: str) -> str:
    """Human-readable title for generated AppBar."""
    return feature_name.replace("_", " ").strip().title() or "Screen"


def render_deterministic_screen_files(
    *,
    feature_name: str,
    screen_class: str,
    uses_svg: bool,
    use_auto_route: bool,
    responsive_enabled: bool,
    max_web_width: int,
    cluster_widget_imports: list[str] | None = None,
    architecture: Architecture = "feature_first",
    package_name: str = "demo_app",
    use_package_imports: bool = True,
    state_management_type: str = "none",
    use_scaffold: bool = True,
) -> dict[str, str]:
    """Render a screen that delegates UI to the deterministic layout file."""
    renderer = DartRenderer()
    layout_class = f"{to_pascal_case(feature_name)}Layout"
    if responsive_enabled:
        body = f"GeneratedScreenShell(child: const {layout_class}())"
    else:
        body = f"const {layout_class}()"
    if use_scaffold:
        title = _screen_app_bar_title(feature_name).replace("'", "\\'")
        root_widget = f"""Scaffold(
      appBar: AppBar(title: Text('{title}', textScaler: textScaler)),
      body: {body},
    )"""
    else:
        root_widget = body
    auto_route = "@RoutePage()\n" if use_auto_route else ""
    screen_code = f"""{auto_route}class {screen_class} extends StatelessWidget {{
  const {screen_class}({{super.key}});

  @override
  Widget build(BuildContext context) {{
    final textScaler = MediaQuery.textScalerOf(context);
    return {root_widget};
  }}
}}"""
    return renderer.render_generation_files(
        FlutterGenerationResponse(screen_code=screen_code),
        feature_name=feature_name,
        uses_svg=uses_svg,
        use_auto_route=use_auto_route,
        responsive_enabled=responsive_enabled,
        max_web_width=max_web_width,
        layout_import=f"{feature_name}_layout",
        extra_widget_imports=cluster_widget_imports,
        screen_only=True,
        architecture=architecture,
        package_name=package_name,
        use_package_imports=use_package_imports,
        state_management_type=state_management_type,
    )
