// Snapshot: plan
// DEBUG BUNDLE — not for compilation.
// Feature: niyama_order
// Single-file view of screen + inlined widgets/layout from this generation run.
// Generated by figma-flutter-agent.
// FFA_RUN_ID: fb369ccec310

import 'package:flutter/material.dart';
import 'package:flutter/gestures.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:test/theme/app_colors.dart';
import 'package:test/theme/app_spacing.dart';
import 'package:test/theme/app_elevation.dart';
import 'package:test/generated/niyama_order_chunk_00f13e69.dart';
import 'package:test/theme/app_layout.dart';

// --- begin lib/widgets/home_indicator_widget.dart ---
class HomeIndicatorWidget extends StatelessWidget {
  const HomeIndicatorWidget({super.key});

  @override
  Widget build(BuildContext context) {
    return SizedBox(width: 375.0, height: 34.0, child: ClipRect(child: Align(alignment: Alignment.topCenter, child: OverflowBox(alignment: Alignment.topCenter, maxHeight: 5.0, child: Container(width: 134.0, height: 5.0, decoration: BoxDecoration(color: Color(0xFFFFFFFF), borderRadius: BorderRadius.circular(100.0)))))));
  }
}
// --- end lib/widgets/home_indicator_widget.dart ---

// --- begin lib/widgets/order_bottom_bar_widget.dart ---
import 'dart:ui' show ImageFilter;

class OrderBottomBarWidget extends StatelessWidget {
  const OrderBottomBarWidget({super.key});

  @override
  Widget build(BuildContext context) {
    return SizedBox(width: 375.0, height: 112.0, child: DecoratedBox(decoration: BoxDecoration(boxShadow: [BoxShadow(offset: Offset(0.0, 2.0), blurRadius: 4.3, spreadRadius: 0.0, color: Color(0x33000000))]), child: ClipRRect(borderRadius: BorderRadius.only(topLeft: Radius.circular(16), topRight: Radius.circular(16), bottomRight: Radius.circular(0), bottomLeft: Radius.circular(0)), child: BackdropFilter(filter: ImageFilter.blur(sigmaX: 10.0, sigmaY: 10.0), child: Container(decoration: BoxDecoration(color: Color(0xCC000000).withOpacity(0.72)), child: Container(width: 375.0, decoration: BoxDecoration(borderRadius: BorderRadius.only(topLeft: Radius.circular(16), topRight: Radius.circular(16), bottomRight: Radius.circular(0), bottomLeft: Radius.circular(0))), foregroundDecoration: BoxDecoration(border: Border.all(color: Color(0xFFFFFFFF), width: 0.3333333333333333), borderRadius: BorderRadius.only(topLeft: Radius.circular(16), topRight: Radius.circular(16), bottomRight: Radius.circular(0), bottomLeft: Radius.circular(0))), child: Padding(padding: const EdgeInsets.fromLTRB(0.0, 14.0, 0.0, 0.0), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.start, crossAxisAlignment: CrossAxisAlignment.stretch, spacing: 14.0, children: [Padding(padding: const EdgeInsets.fromLTRB(14.0, 0.0, 14.0, 0.0), child: Row(mainAxisAlignment: MainAxisAlignment.start, crossAxisAlignment: CrossAxisAlignment.start, spacing: 10.0, children: [Expanded(child: SizedBox(height: 50.0, child: const PlaceOrderButtonWidget()))])), SizedBox(width: 375.0, height: 34.0, child: SizedBox(width: 375.0, height: 34.0, child: SizedBox(width: 375.0, child: const HomeIndicatorWidget())))]))))))));
  }
}
// --- end lib/widgets/order_bottom_bar_widget.dart ---

// --- begin lib/widgets/place_order_button_widget.dart ---
class PlaceOrderButtonWidget extends StatelessWidget {
  const PlaceOrderButtonWidget({super.key});

  @override
  Widget build(BuildContext context) {
    final textScaler = MediaQuery.textScalerOf(context);
    return SizedBox(width: 347.0, height: 50.0, child: Container(height: 50.0, decoration: BoxDecoration(color: Color(0xFFED9B33), borderRadius: BorderRadius.circular(12.0)), child: Padding(padding: const EdgeInsets.fromLTRB(20.0, 14.0, 20.0, 14.0), child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.center, spacing: 10.0, children: [Flexible(fit: FlexFit.loose, flex: 0, child: SizedBox(height: 22.0, child: Semantics(label: 'Оформить заказ на 1 367 ₽', child: Text('Оформить заказ на 1 367 ₽', style: Theme.of(context).textTheme.bodyMedium?.copyWith(color: Color(0xFF000000), fontSize: 17.0, fontWeight: FontWeight.w600, letterSpacing: -0.41), textScaler: textScaler, strutStyle: StrutStyle(fontSize: 17, height: 1.29, forceStrutHeight: true), textAlign: TextAlign.right))))]))));
  }
}
// --- end lib/widgets/place_order_button_widget.dart ---

// --- begin lib/generated/niyama_order_layout.dart ---
// <geometry-planner>

/// Deterministic layout generated from the Figma clean design tree.
class NiyamaOrderLayout extends StatelessWidget {
  const NiyamaOrderLayout({super.key});

  @override
  Widget build(BuildContext context) {
    return Material(color: Color(0xFF000000), child: Material(color: Colors.transparent, child: SingleChildScrollView(child: SizedBox(width: 375.0, height: 1483.0, child: Align(alignment: Alignment.topLeft, child: OverflowBox(alignment: Alignment.topLeft, maxHeight: 1483.0, child: Stack(clipBehavior: Clip.hardEdge, children: [_buildBackground(context), _buildAdss(context), _buildBgBlur(context), _buildModal(context)])))))));
  }

  Widget _buildAdss(BuildContext context) {
    final textScaler = MediaQuery.textScalerOf(context);
    return Positioned(left: 0.0, top: 616.0, width: 375.0, key: ValueKey('figma-4408_44908'), child: RepaintBoundary(child: Container(width: 375.0, decoration: BoxDecoration(color: Color(0xFF000000)), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.start, crossAxisAlignment: CrossAxisAlignment.stretch, children: [Container(width: 375.0, decoration: BoxDecoration(color: Color(0xFF000000)), child: Padding(padding: const EdgeInsets.fromLTRB(0.0, 32.0, 0.0, 32.0), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.start, crossAxisAlignment: CrossAxisAlignment.stretch, spacing: 20.0, children: [Padding(padding: const EdgeInsets.fromLTRB(14.0, 0.0, 0.0, 0.0), child: Row(mainAxisAlignment: MainAxisAlignment.start, crossAxisAlignment: CrossAxisAlignment.center, children: [Flexible(fit: FlexFit.loose, flex: 0, child: SizedBox(height: 28.0, child: Semantics(label: 'Добавить к заказу?', child: Text('Добавить к заказу?', style: Theme.of(context).textTheme.displayLarge?.copyWith(color: Color(0xFFFFFFFF), fontSize: 22.0, fontWeight: FontWeight.w600, letterSpacing: 0.35), textScaler: textScaler, strutStyle: StrutStyle(fontSize: 22, height: 1.27, forceStrutHeight: true, leading: 0.03), textAlign: TextAlign.left))))])), SizedBox(width: 375.0, height: 239.0, child: Stack(fit: StackFit.expand, clipBehavior: Clip.none, children: [Positioned.fill(child: Image.asset('assets/images/sauces.png', fit: BoxFit.cover))]))]))), const OrderBottomBarWidget()]))));
  }
  Widget _buildBgBlur(BuildContext context) {
    return Positioned(left: 0.0, top: 0.0, width: 375.0, height: 812.0, key: ValueKey('figma-4408_44887'), child: ClipRect(child: Align(alignment: Alignment.topCenter, child: OverflowBox(alignment: Alignment.topCenter, maxHeight: 812.0, child: RepaintBoundary(child: Container(width: 375.0, height: 812.0, decoration: BoxDecoration(color: Color(0x99000000))))))));
  }
  Widget _buildModal(BuildContext context) {
    return Positioned(left: 0.0, top: 40.0, width: 375.0, height: 1213.0, key: ValueKey('figma-4408_44888'), child: RepaintBoundary(child: const FigmaChunk00F13E69()));
  }
  Widget _buildBackground(BuildContext context) {
    return IgnorePointer(child: RepaintBoundary(child: Stack(clipBehavior: Clip.none, children: [Positioned(left: 0.0, top: 0.0, width: 375.0, height: 40.0, key: ValueKey('figma-4408_44886'), child: ClipRect(child: Align(alignment: Alignment.topCenter, child: OverflowBox(alignment: Alignment.topCenter, maxHeight: 40.0, child: RepaintBoundary(child: GestureDetector(onTap: () { /* <custom-code:figma-4408_44886:card-action> */ }, behavior: HitTestBehavior.opaque, child: SvgPicture.asset('assets/illustrations/sistem_head_4408_44886.svg', width: 375.0, height: 40.0, fit: BoxFit.contain)))))))])));
  }
}
// --- end lib/generated/niyama_order_layout.dart ---

// --- begin lib/features/niyama_order/niyama_order_screen.dart ---
class NiyamaOrderScreen extends StatelessWidget {
  const NiyamaOrderScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return const NiyamaOrderLayout();
  }
}
// --- end lib/features/niyama_order/niyama_order_screen.dart ---
