// DEBUG BUNDLE — not for compilation.
// Feature: sleep_music
// Single-file view of screen + inlined widgets/layout from this generation run.
// Generated by figma-flutter-agent.

import 'package:flutter/material.dart';
import 'package:flutter/gestures.dart';
import 'package:demo_app/theme/app_colors.dart';
import 'package:demo_app/theme/app_spacing.dart';
import 'package:demo_app/theme/app_elevation.dart';
import 'package:demo_app/theme/app_layout.dart';

// --- begin lib/generated/sleep_music_layout.dart ---
// <geometry-planner>

/// Deterministic layout generated from the Figma clean design tree.
class SleepMusicLayout extends StatelessWidget {
  const SleepMusicLayout({super.key});

  @override
  Widget build(BuildContext context) {
    return Material(color: Colors.transparent, child: const SizedBox.shrink());
  }
}
// --- end lib/generated/sleep_music_layout.dart ---

// --- begin lib/features/sleep_music/sleep_music_screen.dart ---
/// Responsive shell injected by the generator for web/tablet max width.
class GeneratedScreenShell extends StatelessWidget {
  const GeneratedScreenShell({
    super.key,
    required this.child,
    this.maxWebWidth = 1200,
  });

  final Widget child;
  final double maxWebWidth;

  static final double _artboardPreviewWidth = double.tryParse(
        const String.fromEnvironment('FIGMA_FLUTTER_ARTBOARD_PREVIEW_WIDTH'),
      ) ??
      0;
  static final double _artboardPreviewHeight = double.tryParse(
        const String.fromEnvironment('FIGMA_FLUTTER_ARTBOARD_PREVIEW_HEIGHT'),
      ) ??
      0;

  @override
  Widget build(BuildContext context) {
    if (_artboardPreviewWidth > 0 && _artboardPreviewHeight > 0) {
      return Align(
        alignment: Alignment.topLeft,
        child: ClipRect(
          child: SizedBox(
            width: _artboardPreviewWidth,
            height: _artboardPreviewHeight,
            child: ColoredBox(
              color: Theme.of(context).scaffoldBackgroundColor,
              child: child,
            ),
          ),
        ),
      );
    }
    final layout = Theme.of(context).extension<AppLayoutExtension>();
    final resolvedMaxWidth = layout?.maxWebWidth ?? maxWebWidth;
    return Scaffold(
      backgroundColor: Theme.of(context).scaffoldBackgroundColor,
      body: LayoutBuilder(
        builder: (context, constraints) {
          final media = MediaQuery.sizeOf(context);
          final width = constraints.maxWidth.isFinite && constraints.maxWidth > 0
              ? constraints.maxWidth
              : media.width;
          final horizontalPadding = AppBreakpoints.horizontalPadding(width);
          final contentMaxWidth = AppBreakpoints.contentMaxWidth(width, resolvedMaxWidth);
          final Widget body = Align(
            alignment: Alignment.topCenter,
            child: ConstrainedBox(
              constraints: BoxConstraints(maxWidth: contentMaxWidth),
              child: Padding(
                padding: EdgeInsets.symmetric(horizontal: horizontalPadding),
                child: child,
              ),
            ),
          );
          return body;
        },
      ),
    );
  }
}

class SleepMusicScreen extends StatelessWidget {
  static final double _artboardPreviewWidth = double.tryParse(
    const String.fromEnvironment('FIGMA_FLUTTER_ARTBOARD_PREVIEW_WIDTH'),
  ) ??
      0;
  static final double _artboardPreviewHeight = double.tryParse(
    const String.fromEnvironment('FIGMA_FLUTTER_ARTBOARD_PREVIEW_HEIGHT'),
  ) ??
      0;

  const SleepMusicScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return GeneratedScreenShell(child: const SleepMusicLayout());
  }
}
// --- end lib/features/sleep_music/sleep_music_screen.dart ---
